[general]
default-menu-cmd=fzf

[ui]
column-email={{index (.From | emails) 0}}
column-from={{ .From | emails | join ", " }}
column-size={{.Size | humanReadable}} # Adds email size column
column-subject = {{.ThreadPrefix}}{{.Subject}}
column-to={{ .To | emails | join ", " }}
fuzzy-complete=true
index-columns=flags:4,from<20%,subject,to<15%,date>=,size>=
select-last-message=true
sort=from -r date
# styleset-name=rose-pine
threading-enabled=true

[statusline]

[viewer]

[compose]

file-picker-cmd=fzf --multi --query=%s

[multipart-converters]

[filters]
.headers=colorize
message/delivery-status=colorize
message/rfc822=colorize
text/calendar=calendar
text/html=! html
text/plain = wrap -w 120 | colorize

[openers]

[hooks]

[templates]

