[global]
chord_timeout = 50

[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
# capslock = overload(control, esc)
capslock = overload(meta, esc)  # meta = Super key

# Remaps the escape key to capslock
esc = capslock

# chords: jk mapped to esc, ui -> tab
j+k = esc
u+i = tab
