[global]
chord_timeout = 50

[ids]

*

[main]

tab = overload(meta, esc) # meta = Super key

capslock = overload(control, esc)  # map capslock to escape when pressed and control when held.
; = overload(ctl, esc)

# Remaps the escape key to capslock
esc = capslock

# chords: jk mapped to esc, ui -> tab
j+k = esc
s+d = tab
