; NOTE: ~\Documents\AutoHotkey\key-remaps.ahk
: INFO:
; https://stackoverflow.com/questions/78384471/how-to-map-capslock-to-esc-and-ctrl-in-autohotkey
;    - *Wildcard: Fires the hotkey even if extra modifiers (in this case Ctrl)
;    are being held down.
;
;    - DownR has an effect similar to physically pressing the key.
;
;    - The Blind mode
;      avoids releasing the modifier keys (Alt, Ctrl, Shift, and Win) if they
;      started out in the down position...
;      Modifier keys are restored differently to allow a Send to turn off a
;      hotkey's modifiers even if the user is still physically holding them down.

; https://www.autohotkey.com/docs/v2/lib/Send.htm#keynames
;
; Key name 	Description
; {F1} - {F24} 	Function keys. For example: {F12} is F12.
; {!} 	!
; {#} 	#
; {+} 	+
; {^} 	^
; {{} 	{
; {}} 	}
; {Enter} 	Enter on the main keyboard
; {Escape} or {Esc} 	Esc
; {Space} 	Space (this is only needed for spaces that appear either at the beginning or the end of the string to be sent -- ones in the middle can be literal spaces)
; {Tab} 	Tab
; {Backspace} or {BS} 	Backspace
; {Delete} or {Del} 	Del
; {Insert} or {Ins} 	Ins
; {Up} 	↑ (up arrow) on main keyboard
; {Down} 	↓ (down arrow) on main keyboard
; {Left} 	← (left arrow) on main keyboard
; {Right} 	→ (right arrow) on main keyboard
; {Home} 	Home on main keyboard
; {End} 	End on main keyboard
; {PgUp} 	PgUp on main keyboard
; {PgDn} 	PgDn on main keyboard
; {CapsLock} 	CapsLock (using SetCapsLockState is more reliable). Sending {CapsLock} might require SetStoreCapsLockMode False beforehand.
; {ScrollLock} 	ScrollLock (see also: SetScrollLockState)
; {NumLock} 	NumLock (see also: SetNumLockState)
; {Control} or {Ctrl} 	Ctrl (technical info: sends the neutral virtual key but the left scan code)
; {LControl} or {LCtrl} 	Left Ctrl (technical info: sends the left virtual key rather than the neutral one)
; {RControl} or {RCtrl} 	Right Ctrl
; {Control down} or {Ctrl down} 	Holds Ctrl down until {Ctrl up} is sent. To hold down the left or right key instead, replace Ctrl with LCtrl or RCtrl.
; {Alt} 	Alt (technical info: sends the neutral virtual key but the left scan code)
; {LAlt} 	Left Alt (technical info: sends the left virtual key rather than the neutral one)
; {RAlt} 	Right Alt (or AltGr, depending on keyboard layout)
; {Alt down} 	Holds Alt down until {Alt up} is sent. To hold down the left or right key instead, replace Alt with LAlt or RAlt.
; {Shift} 	Shift (technical info: sends the neutral virtual key but the left scan code)
; {LShift} 	Left Shift (technical info: sends the left virtual key rather than the neutral one)
; {RShift} 	Right Shift
; {Shift down} 	Holds Shift down until {Shift up} is sent. To hold down the left or right key instead, replace Shift with LShift or RShift.
; {LWin} 	Left Win
; {RWin} 	Right Win
; {LWin down} 	Holds the left Win down until {LWin up} is sent
; {RWin down} 	Holds the right Win down until {RWin up} is sent
; {AppsKey} 	Menu (invokes the right-click or context menu)
; {Sleep} 	Sleep
; {ASC nnnnn}

; Sends an Alt+nnnnn keypad combination, which can be used to generate special characters that don't exist on the keyboard.
;
; To generate printable ASCII characters or other characters from the system's OEM (DOS) code page, specify a number between 1 and 255. DllCall("GetOEMCP", "UInt") returns the current OEM code page number, such as 437 (United States) or 850 (Western Europe).
;
; To generate ANSI characters (standard in most languages), specify a number between 128 and 255, but precede it with a leading zero, e.g. {Asc 0133}. DllCall("GetACP", "UInt") returns the current ANSI code page number, such as 1252 (United States, Western Europe, etc.).
;
; Unicode characters may be generated by specifying a number between 256 and 65535 (without a leading zero). However, this is not supported by all applications. For alternatives, see the section below.
; {U+nnnn}
;
; Sends a Unicode character where nnnn is the hexadecimal value of the character excluding the 0x prefix. This typically isn't needed, because Send and ControlSend automatically support Unicode text.
;
; SendInput() or WM_CHAR is used to send the character and the current Send mode has no effect. Characters sent this way usually do not trigger shortcut keys or hotkeys.
;
; {vkXX}
; {scYYY}
; {vkXXscYYY}
;
;
; Sends a keystroke that has virtual key XX and scan code YYY. For example: Send "{vkFFsc159}". If the sc or vk portion is omitted, the most appropriate value is sent in its place.
;
; The values for XX and YYY are hexadecimal and can usually be determined from the main window's View->Key history menu item. See also: Special Keys
;
; Warning: Combining vk and sc in this manner is valid only with Send.
; {Numpad0} - {Numpad9} 	Numpad digit keys (as seen when NumLock is ON). For example: {Numpad5} is 5.
; {NumpadDot} 	. (numpad period) (as seen when NumLock is ON).
; {NumpadEnter} 	Enter on keypad
; {NumpadMult} 	* (numpad multiplication)
; {NumpadDiv} 	/ (numpad division)
; {NumpadAdd} 	+ (numpad addition)
; {NumpadSub} 	- (numpad subtraction)
; {NumpadDel} 	Del on keypad (this key and the following Numpad keys are used when NumLock is OFF)
; {NumpadIns} 	Ins on keypad
; {NumpadClear} 	Clear key on keypad (usually 5 when NumLock is OFF).
; {NumpadUp} 	↑ (up arrow) on keypad
; {NumpadDown} 	↓ (down arrow) on keypad
; {NumpadLeft} 	← (left arrow) on keypad
; {NumpadRight} 	→ (right arrow) on keypad
; {NumpadHome} 	Home on keypad
; {NumpadEnd} 	End on keypad
; {NumpadPgUp} 	PgUp on keypad
; {NumpadPgDn} 	PgDn on keypad
; {Browser_Back} 	Select the browser "back" button
; {Browser_Forward} 	Select the browser "forward" button
; {Browser_Refresh} 	Select the browser "refresh" button
; {Browser_Stop} 	Select the browser "stop" button
; {Browser_Search} 	Select the browser "search" button
; {Browser_Favorites} 	Select the browser "favorites" button
; {Browser_Home} 	Launch the browser and go to the home page
; {Volume_Mute} 	Mute/unmute the master volume. Usually equivalent to SoundSetMute -1.
; {Volume_Down} 	Reduce the master volume. Usually equivalent to SoundSetVolume -5.
; {Volume_Up} 	Increase the master volume. Usually equivalent to SoundSetVolume "+5".
; {Media_Next} 	Select next track in media player
; {Media_Prev} 	Select previous track in media player
; {Media_Stop} 	Stop media player
; {Media_Play_Pause} 	Play/pause media player
; {Launch_Mail} 	Launch the email application
; {Launch_Media} 	Launch media player
; {Launch_App1} 	Launch user app1
; {Launch_App2} 	Launch user app2
; {PrintScreen} 	PrtSc
; {CtrlBreak} 	Ctrl+Pause
; {Pause} 	Pause
; {Click [Options]} 	Sends a mouse click using the same options available in the Click function. For example, Send "{Click}" would click the left mouse button once at the mouse cursor's current position, and Send "{Click 100 200}" would click at coordinates 100, 200 (based on CoordMode). To move the mouse without clicking, specify 0 after the coordinates; for example: Send "{Click 100 200 0}". The delay between mouse clicks is determined by SetMouseDelay (not SetKeyDelay).
; {WheelDown}, {WheelUp}, {WheelLeft}, {WheelRight}, {LButton}, {RButton}, {MButton}, {XButton1}, {XButton2}
;
; Sends a mouse button event at the cursor's current position (to have control over position and other options, use {Click} above). The delay between mouse clicks is determined by SetMouseDelay.
;
; LButton and RButton correspond to the primary and secondary mouse buttons. Normally the primary mouse button (LButton) is on the left, but the user may swap the buttons via system settings.
; {Blind} 	Enables the Blind mode, which gives the script more control by disabling a number of things that are normally done automatically to make things generally work as expected. {Blind} must occur at the beginning of the string.
; {Raw} 	Enables the Raw mode, which causes the following characters to be interpreted literally: ^+!#{}. Although {Raw} need not occur at the beginning of the string, once specified, it stays in effect for the remainder of the string.
; {Text} 	Enables the Text mode, which sends a stream of characters rather than keystrokes. Like the Raw mode, the Text mode causes the following characters to be interpreted literally: ^+!#{}. Although {Text} need not occur at the beginning of the string, once specified, it stays in effect for the remainder of the string.


#Requires AutoHotkey v2.0

#SingleInstance Force

; Tap = Esc, Hold = Ctrl+Alt
*CapsLock::Send "{Blind}{LWin down}{LAlt down}{Alt down}"
*CapsLock Up::
{
    Send "{Blind}{LWin up}{LAlt up}{Alt up}"
    If (A_PriorKey = "CapsLock")
        Send "{Esc}"
}

