# Every field is documented in the sample config:
# https://github.com/pimalaya/himalaya/blob/master/config.sample.toml

[accounts.posteo]
default = true
imap.sasl.plain.authcid = "elies@posteo.net"
imap.sasl.plain.passwd.command = "~/.venv/bin/keyring get posteo elies"
imap.server = "imaps://posteo.de:993"
mailbox.alias.inbox = "INBOX"
smtp.sasl.plain.authcid = "elies@posteo.net"
smtp.sasl.plain.passwd.command = "~/.venv/bin/keyring get posteo elies"
smtp.server = "smtps://posteo.de:465"

[accounts.gmail]
imap.sasl.plain.authcid = "francesc.elies@gmail.com"
imap.sasl.plain.passwd.command = "~/.venv/bin/keyring get gmail himalaya"
imap.server = "imaps://imap.gmail.com:993"
mailbox.alias.inbox = "INBOX"
smtp.sasl.plain.authcid = "francesc.elies@gmail.com"
smtp.sasl.plain.passwd.command = "~/.venv/bin/keyring get gmail himalaya"
smtp.server = "smtps://smtp.gmail.com:465"

